sudo: required
services:
    - docker

before_install:
    - docker build -t rajatmaru/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true rajatmaru/docker-react npm run test -- --coverage
    